<?php
namespace backend\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;

class BackendController extends Controller{

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        $behaviors['access'] = [
            'class' => AccessControl::className(),
            'rules' => [
                [
                    'allow' => true,
                    'roles' => ['@'],
                    'matchCallback' => function ($rule, $action) {
                        $action = Yii::$app->controller->action->id;
                        $controller = Yii::$app->controller->id;
                        $route = "$controller/$action";
                        $post = Yii::$app->request->post();
                        if (\Yii::$app->user->can($route)||Yii::$app->user->identity->username==='Superadmin') {
                            return true;
                        }
                    }
                ],
            ],
        ];
        return $behaviors;
    }

    /**
     * {@inheritdoc}
     */
    public function afterAction($action, $result)
    {
        if(Yii::$app->urlManager->baseUrl=="/admin" && !Yii::$app->user->isGuest){
            $action = Yii::$app->controller->action->id;
            $controller = Yii::$app->controller->id;
            $log = new \common\models\Log();
            $log->time=\func::getTimeNow();
            $log->noidung=$controller."/".$action;
            $log->user=Yii::$app->user->identity->username;
            $log->loai="Tracking Backend User";
            $log->banghi="-1";
            if($controller!="default")
                $log->save();
        }
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }
}